nama=input("siapa nama anda?")
print("hallo",nama,"semangat belajar ya!!")
alamat=input("anda dari mana?")
print("ooh anda dari",alamat,"jauh sekali yaaa")
nomertelepon=input("berapa nomer telepon anda?")
print("ooh",nomertelepon,"ini nomer telepon anda baiklah terima kasih!!")
